version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ats_mysql
    environment:
      MYSQL_ROOT_PASSWORD: StimaSukses
      MYSQL_DATABASE: kaggle_resumes
      MYSQL_USER: ats_user
      MYSQL_PASSWORD: StimaSukses
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local